# Generated by scripts/make-formula.sh — do not hand-edit; regenerate for a new tag.
class CmuxSentinel < Formula
  desc "Opinionated cmux sidebar with agent-state rows and AI usage meters"
  homepage "https://github.com/oliver-kriska/cmux-sentinel"
  url "https://github.com/oliver-kriska/cmux-sentinel/archive/refs/tags/v0.2.3.tar.gz"
  sha256 "9238de37b95e2b9f7c9f6daf95de57ae042a1d267aeae06350cfc1c7f723bbb5"
  license "MIT"

  depends_on "jq"
  depends_on :macos

  def install
    # The WHOLE tree, not just bin/: install.sh also deploys sidebars/, hooks/ and
    # the launchd templates, and it locates them relative to itself.
    libexec.install Dir["*"]
    # Deliberately not bin.install_symlink: through a symlink $0 stays in the
    # prefix's bin/, where none of the cmux-*.sh helpers live, and the dispatcher
    # would fail to resolve them. write_exec_script execs the real libexec path.
    bin.write_exec_script libexec/"bin/cmux-sentinel"
  end

  # Caveats print on UPGRADE too, and the upgrade is when this message matters:
  # brew replaces the Cellar copy while launchd keeps running the scripts in ~/bin.
  # FormulaInstaller#caveats gates only on only_deps?/installed_on_request?/quiet?,
  # never on first-install. There is deliberately no post_install: Homebrew 7
  # deprecates it, and post-install runs sandboxed with a temp HOME, so neither it
  # nor a post_install_steps run step could deploy into ~/bin for the user.
  def caveats
    <<~EOS
      Homebrew installed the files; two commands finish the job:

        cmux-sentinel deploy    # sidebar, pollers, launchd agents, hooks -> $HOME
        cmux-sentinel doctor    # confirm the pipeline is wired

      Run 'deploy' after every upgrade too: the launchd agents run the copies in
      ~/bin, so a new formula alone changes nothing that is actually executing.
    EOS
  end

  test do
    assert_match "cmux-sentinel deploy", shell_output("#{bin}/cmux-sentinel help")
    # An unknown command must fail loudly (exit 2), never silently no-op.
    shell_output("#{bin}/cmux-sentinel definitely-not-a-command 2>&1", 2)
  end
end
