# Generated by scripts/make-formula.sh — do not hand-edit; regenerate for a new tag.
class CmuxSentinel < Formula
  desc "Opinionated cmux sidebar with agent-state rows and AI usage meters"
  homepage "https://github.com/oliver-kriska/cmux-sentinel"
  url "https://github.com/oliver-kriska/cmux-sentinel/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "a8eeaea87202d986ab3dd57552b33aeb51219bedc0d8cde55cd72411a0614ef7"
  license "MIT"

  depends_on "jq"
  depends_on :macos

  def install
    # The WHOLE tree, not just bin/: install.sh also deploys sidebars/, hooks/ and
    # the launchd templates, and it locates them relative to itself.
    libexec.install Dir["*"]
    # Deliberately not bin.install_symlink: through a symlink $0 stays in the
    # prefix's bin/, where none of the cmux-*.sh helpers live, and the dispatcher
    # would fail to resolve them. write_exec_script execs the real libexec path.
    bin.write_exec_script libexec/"bin/cmux-sentinel"
  end

  # Homebrew prints caveats only on the FIRST install, never on upgrade — and the
  # message that has to survive an upgrade is exactly this one, because brew
  # updates the Cellar copy while launchd keeps running the scripts in ~/bin.
  def post_install
    ohai "Run 'cmux-sentinel deploy' to install this version into ~/bin and ~/.config"
  end

  def caveats
    <<~EOS
      Homebrew installed the files; two commands finish the job:

        cmux-sentinel deploy    # sidebar, pollers, launchd agents, hooks -> $HOME
        cmux-sentinel doctor    # confirm the pipeline is wired

      Run 'deploy' after every upgrade too: the launchd agents run the copies in
      ~/bin, so a new formula alone changes nothing that is actually executing.
    EOS
  end

  test do
    assert_match "cmux-sentinel deploy", shell_output("#{bin}/cmux-sentinel help")
    # An unknown command must fail loudly (exit 2), never silently no-op.
    shell_output("#{bin}/cmux-sentinel definitely-not-a-command 2>&1", 2)
  end
end
